version: '3.9'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Songlong123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./init-database.sql:/init-database.sql
      - init_status:/var/opt/mssql/init-flag
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 10 && 
        if [ ! -f /var/opt/mssql/init-flag/initialized.flag ]; then
          sqlcmd -S localhost -U sa -P Songlong123 -i /init-database.sql -b &&
          touch /var/opt/mssql/init-flag/initialized.flag;
        fi &&
        tail -f /dev/null
      "

volumes:
  init_status:
